server:
  port: 8080
  servlet:
    context-path: /
  shutdown: graceful

spring:
  application:
    name: medcare-platform


  datasource:
    url: jdbc:mysql://localhost:3306/medcare_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Parth@2005
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: MedcareHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: medcare_super_secret_jwt_key_2024_hackathon_secure_256bit_key_here
    expiration-ms: 86400000
    refresh-expiration-ms: 604800000

logging:
  level:
    com.medcare: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
gemini:
  api:
    key: AIzaSyAo4mmNf0n-4uqc9sF5Gs9unLk6qaRMkVY
    url: https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent


